name 'forj-puppet'
version '0.1.0'
author '(c) Copyright 2014 Hewlett-Packard Development Company, L.P.'
license 'http://www.apache.org/licenses/LICENSE-2.0'
source 'https://review.forj.io'
project_page 'https://forj.io'
summary 'Sets up all puppet required infastructure and manages puppet.conf.  '
description 'Sets up all puppet required infastructure and manages puppet.conf.  
Configured to run puppet under cron/passenger, includes reporting and dashboard.'
